name: Fly Deploy
on: 
  push:
  schedule:
    - cron: '0 4 1 * *'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        run: |
          curl -L https://fly.io/install.sh | sh | FLYCTL_INSTALL=/usr/local sh
          flyctl deploy --detach

